# Generated by Django 5.2 on 2025-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='konten',
            new_name='isi',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
