# Generated by Django 5.2.1 on 2025-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar_judul',
            field=models.ImageField(blank=True, null=True, upload_to='artikel_images/'),
        ),
    ]
